### ISSUE TITLE
temps > 100

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [coriolinus/1brc#1]
Thanks for porting the generator to rust -- very handy to kickstart my own attempt.

I just had some issues because some of the generated floats are >100 for me, which [doesn't seem to be the case for others](https://gist.github.com/Lucretiel/b9d8a2f75c445ba62035fd80adb5fd57/6ac36a58005176d44718e1947f88b6514291676f#file-one-billion-line-challenge-rs-L75).

I'm not quite sure but it seems that the original code simply always uses a standard deviation of 10, while you use a standard deviation sampled from N(10, 2.5)? So it could be that one of the cities ends up with standard deviation around 17.5, which makes it more likely to go over 100 max temperature.

(Either way I suppose the original could probably also generate temps > 100, but probably it's more rare there.)

**Comment by coriolinus** [comment]
Yeah, I noticed that my temp ranges are a bit wide too. Agree with your diagnosis of the cause. That was an intentional deviation from the Java generator, because I didn't think all cities globally actually have the same temperature deviation, and this was the simplest way to vary it.

It shouldn't make a difference, I think, unless you're using some miniature fixed-point math or something to represent the temperature. (Actually, that might be a cool/performant refinement, depending on parsing speed: a temperature is a u16 counting 0.1 degree increments over -100 or something. But nothing in the dataset should be outside the representable range for that type.)

Either way, I think it is not unreasonable for temperatures to exceed 100 if we assume that this is measuring in Fahrenheit. So I don't think I'm going to change it.
